name: PHP Codesniffer

on:
  push:
    branches:
      - '!main'
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  PHP-Codesniffer:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo, phar, reflection, session, simplexml, spl, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib
        coverage: none

    #- name: Validate composer.json and composer.lock
    #  run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Run Composer Installer
      run: composer run-script post-install-cmd || true

    - name: Add VIPCS to PHPCS
      run: |
        vendor/bin/phpcs --config-set installed_paths vendor/automattic/vipwpcs,vendor/wp-coding-standards/wpcs
        vendor/bin/phpcs -i
    
    #- name: Run PHPCodesniffer Installer
    #  run: composer phpcodesniffer-composer-installer
    
    #- name: Load Automattic VIPWPCS
    #  run: composer automattic/vipwpcs
    
    - name: Set default PHPCS Standards
      run: composer set_default

    - name: PHPCS Installed Standards
      run: composer phpcs_i   

    - name: PHPCBF
      run: composer phpcbf  
    
    - name: PHPCS
      run: composer phpcs    

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
